/*

 LIFE_SELECTED.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char TileLabel[] =
{
  0x18,0x18,0x66,0x6E,0x42,0x66,0x81,0xC1,
  0x81,0x83,0x42,0x66,0x66,0x76,0x18,0x18
};

/* End of LIFE_SELECTED.C */
